export const COOKIE_EXPIRATION = 1000 * 60 * 60 * 24 * 7 * 365;
export const COOKIE_NAME = 'auth_token';
export const RATE_LIMIT_TIME = 60;
export const RATE_LIMIT = 50;
export const RATE_LIMIT_PREFIX = 'ratelimit';
export const CONFIRM_USER_PREFIX = 'user-confirmation:';
export const SESSION_PREFIX = `stock-management-session:`;
export const FORGOT_PASSWORD_PREFIX = `forgot-password:`;
export const LAST_LOGIN_PREFIX = 'stock-management-login:'